<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>rkt</string>
  </array>
  <key>name</key>
  <string>Racket</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>begin</key>
      <string>\"</string>
      <key>end</key>
      <string>\"</string>
      <key>name</key>
      <string>string.quoted.double.source.racket</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>('\(|'\[)</string>
      <key>end</key>
      <string>(\)|\])</string>
      <key>name</key>
      <string>string.quoted.double.source.racket</string>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.source.racket</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.variable.source.racket</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\((define)\s+([a-zA-Z0-9_\-?\+^]+)\s*</string>
      <key>name</key>
      <string>meta.variable.source.racket</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>\((define)\s+\(([a-zA-Z0-9_\-?\+^]+)\s+</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.source.racket</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.racket</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\)</string>
      <key>name</key>
      <string>meta.method.racket</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.racket</string>
            </dict>
          </dict>
          <key>match</key>
          <string>(\w|\-|\d)+</string>
          <key>name</key>
          <string>variable.parameter.racket</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.source.racket</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(if|lambda|cond|define|type-case|let|letrec|let!|\#lang|require|test|else|first|butfirst|bf|last|butlast|bl|rest|define-type|define-type-alias|define-struct|not|local|error|super-new|define/public|init|define/private|send|new|let\*|class)[\s\)]</string>
      <key>name</key>
      <string>meta.keywords.source.racket</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(true|false|empty|cons|car|cdr|caar|cadr|cdar|cddr|caaar|caadr|cadar|caddr|cdaar|cdadr|cddar|cdddr|caaaar|caaadr|caadar|caaddr|cadaar|cadadr|caddar|cadddr|cdaaar|cdaadr|cdadar|cdaddr|cddaar|cddadr|cdddar|cddddr)[\s\)]</string>
      <key>name</key>
      <string>constant.language.source.racket</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(0|([1-9][0-9_]*))\b</string>
      <key>name</key>
      <string>constant.numeric.integer.source.racket</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>\;</string>
      <key>end</key>
      <string>$\n</string>
      <key>name</key>
      <string>comment.line.documentation.source.racket</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\'[\d\w\-?!]+</string>
      <key>name</key>
      <string>string.quoted.double.source.racket</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>\#\|</string>
      <key>end</key>
      <string>\|\#</string>
      <key>name</key>
      <string>comment.line.documentation.source.racket</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([\w]+\%)</string>
      <key>name</key>
      <string>storage.type.racket</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.racket</string>
</dict>
</plist>
